### ISSUE TITLE
Refactor the Flogo CLI

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo#395]
**Current behavior:**
The Flogo CLI has become bloated and difficult to manage and maintain.  Over time the flogo build command has grown from a simple build, to be able to handle countless different options, etc. Also, with the growing Flogo Ecosystem, different capabilities may require additional functionality in the CLI. The CLI needs to support a modular approach to handle the growing set of features.

**Expected behavior:**
- [x] New CLI proposal (#327)
- [ ] Enable app testing from the CLI (#290)
- [x] Support for explicitly defining the application JSON to be built (#238)
- [x] Leverage Go modules (#422)

**What is the motivation / use case for changing the behavior?**
Enhance the simplicity and modularity of the Flogo CLI.

**Additional information you deem important (e.g. I need this tomorrow):**

**Comment by mellistibco** [comment]
Closing, as the CLI has been fully rebuilt
